version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_station_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_STATION_USER:-default_user}
      POSTGRES_PASSWORD: ${POSTGRES_STATION_PASSWORD:-default_password}
      POSTGRES_DB: ${POSTGRES_STATION_DB:-default_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
