name: Build & Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger only when a tag starting with "v" is pushed

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from VERSION file
        id: version
        shell: bash
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate version tag
        shell: bash
        run: |
          # Extract the tag name (e.g. "v0.0.9")
          TAG=${GITHUB_REF#refs/tags/}
          # Build the expected tag by prefixing the VERSION file's content with "v"
          EXPECTED_TAG="v${{ steps.version.outputs.version }}"
          echo "Pushed tag: $TAG"
          echo "Expected tag: $EXPECTED_TAG"
          if [ "$TAG" != "$EXPECTED_TAG" ]; then
            echo "Error: The pushed tag does not match the version in the VERSION file."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: presstronic
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Tag the image with both the version and "latest"
          tags: ghcr.io/presstronic/station-bot:${{ steps.version.outputs.version }},ghcr.io/presstronic/station-bot:latest
